### ISSUE TITLE
ETIS-Larib Dataset Link Not Found

### ISSUE THREAD

**Issue by irfanrah** [sing-group/deep-learning-colonoscopy#5]
Hello, 

I want to use ETIS-Larib dataset but the dataset is not found in the link. If someone have link of the dataset or can upload it for me, I will be really appreciate. 

Thank you

**Comment by hlfernandez** [comment]
Hi! It seems that they have changed the URL to: https://polyp.grand-challenge.org/ETISLarib/

We will fix it in the repository, thank you for reporting this issue!

**Comment by irfanrah** [comment]
thank you !
