### ISSUE TITLE
CVC-ClinicDB Dropbox Temporary Disabled

### ISSUE THREAD

**Issue by irfanrah** [sing-group/deep-learning-colonoscopy#6]
Hello. 
I want to download CVC-ClinicDB dataset, for these past day I already tried several time to try to download from that dropbox but the link doesn't seems to be downloadable. Actually, I have found the dataset on  Kaggle ([https://www.kaggle.com/datasets/balraj98/cvcclinicdb](url)). 

However, the kaggle's CVC-ClinicDB was not default split by training, val, and test set like the paper that was used in VideoGAN ([https://arxiv.org/abs/2004.08058](url)) or other papers that used the dataset. Could someone give the spitted version of CVC-ClinicDB dataset. Thank you.

**Comment by hlfernandez** [comment]
Hi again! In this case, we recommend you to write an e-mail to [Jorge Bernal](https://scholar.google.es/citations?user=GsyL_kUAAAAJ&hl=en) (one of the main authors of the dataset). You probably can find his e-mail in one of his recent publications.

**Comment by irfanrah** [comment]
Okay. Thank you!
